//! Hosts that are never intercepted, compiled in.
//!
//! Sources, fetched 2026-09-25:
//! - Apple: every host in support.apple.com/101555, collapsed to `*.domain` where the
//!   article lists the whole domain or several of its hosts.
//! - AdGuard HttpsExclusions (github.com/AdguardTeam/HttpsExclusions) at commit
//!   a8eda6ecc184cc7000436302d64fb932d5205fe0 (2026-09-14): all of
//!   `exclusions/sensitive.txt`, and the second-level `.com`, `.org` and `.net` domains of
//!   `exclusions/banks.txt`. The rest of banks.txt (about 3,600 domains, mostly regional
//!   banks, 1,439 of them German) is left to pin learning and the user list. AdGuard excludes
//!   each listed domain with its subdomains, so every entry becomes `*.domain`. Entries
//!   limited to a desktop app (`$app=`) are left out.
//!
//! Each group is sorted; a host listed in an earlier group is not repeated.

/// The compiled-in passthrough patterns, in [`crate::HostPattern`] syntax.
pub fn bundled_passthrough() -> &'static [&'static str] {
    BUNDLED
}

#[rustfmt::skip]
static BUNDLED: &[&str] = &[
    // Apple, support article 101555 "Use Apple products on enterprise networks"
    // (published 2026-08-07): Apple services fail when HTTPS is intercepted.
    "*.apple", "*.apple-cloudkit.com", "*.apple-dns.net", "*.apple-livephotoskit.com",
    "*.apple-mapkit.com", "*.apple.com", "*.appleschoolcontent.com", "*.apzones.com",
    "*.axm-usercontent-apple.com", "*.cdn-apple.com", "*.icloud-content.com", "*.icloud.com",
    "*.icloud.com.cn", "*.itunes.com", "*.mzstatic.com", "*.vertexsmb.com",
    "appldnld.apple.com.edgesuite.net", "apple-relay.cloudflare.com",
    "apple-relay.fastly-edge.com", "cp4.cloudflare.com", "crl3.digicert.com", "crl4.digicert.com",
    "ocsp.digicert.cn", "ocsp.digicert.com",

    // AdGuard HttpsExclusions exclusions/sensitive.txt: identity, password managers,
    // health, government and other services with sensitive personal information.
    "*.1177.se", "*.1password.ca", "*.1password.com", "*.1password.eu", "*.4user.yeskey.or.kr",
    "*.account.idocs.kz", "*.accounts.google.com", "*.accounts.kakao.com",
    "*.agenciatributaria.gob.es", "*.anaf.ro", "*.anonaddy.com", "*.app.deel.com",
    "*.app.traderepublic.com", "*.apps.cybonline.co.uk", "*.bbss.softbankbb.co.jp",
    "*.besoklegen.no", "*.binance.com", "*.bitwarden.com", "*.bitwarden.eu", "*.bolagsverket.se",
    "*.cable.auth.com", "*.cable.ua5v.com", "*.canadapost.ca", "*.cdn-secuchart.com",
    "*.cert.vno.co.kr", "*.certapi.yeskey.or.kr", "*.certcld.yeskey.or.kr", "*.certsign.ro",
    "*.cfg.smt.docomo.ne.jp", "*.checkout.bambora.com", "*.clave.gob.es", "*.cmbchina.com",
    "*.cnisnet.inss.gov.br", "*.completeid.com", "*.connect.auone.jp", "*.cra-arc.gc.ca",
    "*.dashlane.com", "*.dec.fazenda.df.gov.br", "*.digisign.ro", "*.diskstation.me",
    "*.dscloud.biz", "*.dscloud.me", "*.dscloud.mobi", "*.dsmynas.com", "*.dsmynas.org",
    "*.e-tjanster.1177.se", "*.ebs.ru", "*.ekb.esplus.ru", "*.enclave.ua5v.com", "*.enpass.io",
    "*.equifax.com", "*.experian.com", "*.f-cdn.com", "*.f-secure.com", "*.familyds.com",
    "*.familyds.net", "*.familyds.org", "*.fastmail.com", "*.fido.kt.com", "*.freelancer.ca",
    "*.freelancer.cl", "*.freelancer.cn", "*.freelancer.co.id", "*.freelancer.co.it",
    "*.freelancer.co.uk", "*.freelancer.com", "*.freelancer.com.au", "*.freelancer.com.bd",
    "*.freelancer.is", "*.freelancer.jp", "*.freelancer.ph", "*.freshbooks.com", "*.gate.io",
    "*.go.kr", "*.gorzdrav.spb.ru", "*.gosuslugi.ru", "*.gov.au", "*.gov.in", "*.gov.kr",
    "*.gov.pl", "*.gov.rs", "*.gov.ru", "*.gov.tw", "*.hanko.io", "*.home.mijngezondheid.net",
    "*.hotdoc.com.au", "*.hrblock.com", "*.i234.me", "*.id.biltema.com", "*.id.pilet.ee",
    "*.id.smt.docomo.ne.jp", "*.id.yandex.by", "*.id.yandex.com", "*.id.yandex.com.tr",
    "*.id.yandex.kz", "*.id.yandex.ru", "*.id.yandex.ua", "*.identity.idocs.kz",
    "*.identity.virginmedia.com", "*.idnotify.com", "*.idwatchdog.com", "*.inspectiamuncii.ro",
    "*.intelink.gov", "*.kashflow.com", "*.kau.gov.hu", "*.kauth.kakao.com", "*.kontur-ca.ru",
    "*.kronofogden.se", "*.kurlypay.co.kr", "*.lastpass.com", "*.lifelock.com",
    "*.lisa.motivtelecom.ru", "*.lk.billing74.ru", "*.lk.megafon.ru", "*.lk.sesb.ru",
    "*.lkk-ekb.esplus.ru", "*.login.kt.com", "*.login.live.com", "*.mail.tutanota.com",
    "*.mailbox.org", "*.mailfence.com", "*.meu.inss.gov.br", "*.mexc.com", "*.mijnpazio.nl",
    "*.mil", "*.mos.ru", "*.mvd.dor.ga.gov", "*.my.softbank.jp", "*.mydocomo.com", "*.myds.me",
    "*.myob.com", "*.navyfederal.org", "*.nid.naver.com", "*.nordpass.com",
    "*.nwdealer.megafon.ru", "*.ok.webhop.net", "*.onpointcu.com", "*.papara.com",
    "*.passport.yandex.by", "*.passport.yandex.com", "*.passport.yandex.com.tr",
    "*.passport.yandex.kz", "*.passport.yandex.ru", "*.passport.yandex.ua", "*.pay.naver.com",
    "*.paypal-topup.ee", "*.posteo.de", "*.prestigecu.org", "*.proton.me", "*.protonmail.ch",
    "*.protonmail.com", "*.protonvpn.com", "*.quickconnect.to", "*.raonsecure.co.kr",
    "*.raonsecure.com", "*.receiptbank.com", "*.receita.economia.gov.br", "*.roboform.com",
    "*.rzd.ru", "*.sdk.yeskey.or.kr", "*.secuchart.com", "*.securesafe.com", "*.seg-social.es",
    "*.signal-iduna.de", "*.simplelogin.io", "*.skatteverket.se", "*.sophos.com", "*.synology.me",
    "*.termius.com", "*.tikker.emta.ee", "*.transunion.com", "*.trbinance.com",
    "*.trueidentity.com", "*.trustedid.com", "*.turkiye.gov.tr", "*.tutanota.com",
    "*.uwzorgonline.nl", "*.vd.l.qq.com", "*.web.whatsapp.com", "*.websign.ro",
    "*.workflow.idocs.kz", "*.xero.com", "*.zakupki.gov.ru",

    // AdGuard HttpsExclusions exclusions/banks.txt: second-level .com, .org and .net
    // domains (banks, card issuers, payment processors, brokers, exchanges).
    "*.1stnorcalcu.org", "*.2checkout.com", "*.53.com", "*.abanca.com", "*.abchina.com",
    "*.accessbankplc.com", "*.acledabank-internetbanking.com", "*.acorns.com",
    "*.acs-education.com", "*.adelfibanking.com", "*.adyen.com", "*.agranisme.org", "*.akbank.com",
    "*.alahli.com", "*.alawwalbank.com", "*.alinma.com", "*.alipay.com", "*.allegacy.org",
    "*.alliantcreditunion.com", "*.alliantcreditunion.org", "*.ally.com", "*.altbank.com",
    "*.amedigital.com", "*.amerantbank.com", "*.americanexpress.com", "*.amundi-tc.com",
    "*.anz.com", "*.apsiyon.com", "*.atabank.com", "*.auxmoney.com", "*.avangate.com",
    "*.axisbank.com", "*.bancnetonline.com", "*.bancoactivo.com", "*.bancocajasocial.com",
    "*.bancodebogota.com", "*.bancoexterior.com", "*.bancofinandina.com", "*.bancoldex.com",
    "*.bancomer.com", "*.bancrecerdigital.com", "*.bancsabadell.com", "*.banesconline.com",
    "*.bangkokbank.com", "*.bankalbilad.com", "*.bankchb.com", "*.bankcomm.com", "*.bankinter.com",
    "*.bankofamerica.com", "*.bankofbaku.com", "*.bankofbeirut.com", "*.banorte.com",
    "*.banplusonline.com", "*.barclaycardus.com", "*.bbacbank.com", "*.bcblbd.com", "*.bcu.org",
    "*.becu.org", "*.betterment.com", "*.bhf-bank.com", "*.bidv.com", "*.bil.com",
    "*.billdesk.com", "*.bitfinex.com", "*.bitget.com", "*.bitpanda.com", "*.bitso.com",
    "*.bitstamp.net", "*.bittrex.com", "*.bitwala.com", "*.bity.com", "*.blockfi.com",
    "*.blombank.com", "*.bmo.com", "*.bmoharris.com", "*.bnpparibas.com", "*.bobibanking.com",
    "*.bochk.com", "*.boursobank.com", "*.bpcprocessing.com", "*.bpiexpressonline.com",
    "*.btc-e.com", "*.btgpactual.com", "*.btpn.com", "*.bunq.com", "*.bybit.com",
    "*.caixa-enginyers.com", "*.campuscu.com", "*.capfed.com", "*.capitalone.com", "*.cardpay.com",
    "*.cbcfcu.org", "*.ccb.com", "*.ccservicing.com", "*.changelly.com", "*.chase.com",
    "*.chime.com", "*.chinatrust.com", "*.cibc.com", "*.citi.com", "*.citibankonline.com",
    "*.citizensbank.com", "*.citizensbankonline.com", "*.citybankplc.com", "*.cnb.com",
    "*.coastal24.com", "*.coastalbank.com", "*.coastcapitalsavings.com", "*.cobinhood.com",
    "*.coinbase.com", "*.colpatria.com", "*.combankdigital.com", "*.commerzfinanz.com",
    "*.computershare.com", "*.copayco.com", "*.credit-suisse.com", "*.creditbank.com",
    "*.creditdnepr.com", "*.creditonebank.com", "*.criptointercambio.com", "*.ctbcbank.com",
    "*.currency.com", "*.danamonline.com", "*.danskebank.com", "*.davivienda.com", "*.db.com",
    "*.dcu-online.org", "*.dcu.org", "*.desjardins.com", "*.devbnkphl.com", "*.dhakabankltd.com",
    "*.dhbbank.com", "*.directnet.com", "*.discover.com", "*.docfcu.org", "*.dutchbanglabank.com",
    "*.dvbbank.com", "*.e-bankofbaku.com", "*.eastwestbanker.com", "*.ebase.com", "*.ecommpay.com",
    "*.elevationsbanking.com", "*.elevationscu.com", "*.ellisbank.com", "*.emiratesnbd.com",
    "*.enpara.com", "*.etrade.com", "*.eurobank-ua.com", "*.evobanco.com", "*.fairfx.com",
    "*.farmersebank.com", "*.fastbill.com", "*.fbtonline.com", "*.fbtonline.net", "*.fbwebpos.com",
    "*.fednetbank.com", "*.feniciabank.com", "*.fidelity.com", "*.finansonline.com",
    "*.finecobank.com", "*.firstbankcard.com", "*.firsttechfed.com", "*.fnbba.com",
    "*.fosterswiss.com", "*.frostbank.com", "*.fsibplc.com", "*.ftx.com", "*.fubon.com",
    "*.getpenta.com", "*.globalhbl.com", "*.greensill-bank.com", "*.grenke.net",
    "*.grenkeonline.com", "*.growfinancial.org", "*.grupobancolombia.com", "*.gtbank.com",
    "*.gunaybank.com", "*.hanabank.com", "*.hangseng.com", "*.harrisbank.com", "*.hdfcbank.com",
    "*.hellenicnetbanking.com", "*.hellostake.com", "*.hitbtc.com", "*.hlebroking.com",
    "*.holvi.com", "*.hsbc.com", "*.hsbcnet.com", "*.hsbcprivatebank.com", "*.hubank.com",
    "*.huntington.com", "*.ibanking-services.com", "*.icicibank.com", "*.icon25-bank.com",
    "*.idbi.com", "*.idbibank.com", "*.independentreserve.com", "*.inetpayonline.com",
    "*.ingonline.com", "*.ingwb.com", "*.inicis.com", "*.instamojo.com",
    "*.interactivebrokers.com", "*.internetpanin.com", "*.intesasanpaolo.com", "*.jago.com",
    "*.jenius.com", "*.jkopay.com", "*.juliusbaer.com", "*.kbstar.com", "*.kebhana.com",
    "*.key.com", "*.kgibank.com", "*.klarna.com", "*.klikbca.com", "*.kokobank.com",
    "*.kontist.com", "*.kraken.com", "*.kreditprombank.com", "*.krungsri.com",
    "*.krungsribizonline.com", "*.krungsrionline.com", "*.ktbnetbank.com", "*.kucoin.com",
    "*.leboutique.com", "*.legalandgeneral.com", "*.leomoney.com", "*.lgbbank.com", "*.liqpay.com",
    "*.lloydsbank.com", "*.localbitcoins.com", "*.localethereum.com", "*.lzo.com",
    "*.m1finance.com", "*.marcus.com", "*.marinecu.com", "*.maritimebank.com",
    "*.master-capital.org", "*.masterpass.com", "*.mctcu.org", "*.meabank.com", "*.mebytmb.com",
    "*.megabank.net", "*.memberdirect.net", "*.mercantilbanco.com", "*.metzler.com",
    "*.midoregon.com", "*.mitfcu.org", "*.ml.com", "*.mobikwik.com", "*.modhumotibankltd.com",
    "*.mohela.com", "*.monese.com", "*.monzo.com", "*.mtochka.com", "*.myetherwallet.com",
    "*.myfedloan.org", "*.mymerrill.com", "*.myoccu.org", "*.myvoba.com", "*.n26.com",
    "*.natwest.com", "*.neteller.com", "*.netpnb.com", "*.netteller.com", "*.nonghyup.com",
    "*.nordea.com", "*.nsandi.com", "*.nwolb.com", "*.o-bank.com", "*.oddo-bhf.com",
    "*.oneaccount.com", "*.onfastspring.com", "*.onlinebanking-ibb-ag.com", "*.optumbank.com",
    "*.oregonstatecu.com", "*.oschad24.com", "*.pagbrasil.com", "*.palmettohealthcu.org",
    "*.payco.com", "*.payeer.com", "*.paykun.com", "*.payonlinesystem.com", "*.paypal-nakit.com",
    "*.paypal.com", "*.paypalobjects.com", "*.payproglobal.com", "*.paytm.com", "*.paytr.com",
    "*.payture.com", "*.pbbdirekt.com", "*.pbebank.com", "*.pcbac.com", "*.pearler.com",
    "*.penfed.org", "*.picpay.com", "*.pictet.com", "*.piraeusbank.com", "*.plategka.com",
    "*.plimus.com", "*.pnc.com", "*.pocketsmith.com", "*.portaldepagosmercantil.com",
    "*.priovtb.com", "*.privatbank1891.com", "*.prosperitybankusa.com", "*.pxpayplus.com",
    "*.qantas.com", "*.qantasmoney.com", "*.qiwi.com", "*.qnb.com", "*.qnbfinansbank.com",
    "*.questrade.com", "*.razorpay.com", "*.rbcroyalbank.com", "*.rblbank.com", "*.rbsdigital.com",
    "*.rbsinternational.com", "*.rcbconline-corporate.com", "*.rcbconlinebanking.com",
    "*.rcuonline.org", "*.redwoodcu.org", "*.revolut.com", "*.rfcu.com", "*.riyadbank.com",
    "*.robinhood.com", "*.rusnarbank.com", "*.russobank.com", "*.sabb.com", "*.saferpay.com",
    "*.samba.com", "*.sampathvishwa.com", "*.samsungpop.com", "*.santanderbank.com",
    "*.sberbank.com", "*.sbicard.com", "*.sbiepay.com", "*.sc.com", "*.scbeasy.com",
    "*.schwab.com", "*.scotiabank.com", "*.secureinternetbank.com", "*.securitybank.com",
    "*.selco.org", "*.sendwyre.com", "*.settrade.com", "*.sharesight.com", "*.shinhan.com",
    "*.shinseibank.com", "*.signicat.com", "*.simple.com", "*.simplii.com", "*.sinopac.com",
    "*.smbc-card.com", "*.societegenerale.com", "*.sorexpay.com", "*.southindianbank.com",
    "*.spectrocoin.com", "*.sslcommerz.com", "*.stanbicibtcbank.com", "*.starlingbank.com",
    "*.start2pay.com", "*.stripe.com", "*.suncoast.com", "*.td.com", "*.tdameritrade.com",
    "*.tdbank.com", "*.tdcanadatrust.com", "*.tescobank.com", "*.theinstapay.com",
    "*.theworldexchange.net", "*.tiaa.org", "*.tiscoasset.com", "*.titanvest.com",
    "*.tmbdirect.com", "*.tochka.com", "*.tossbank.com", "*.tossinvest.com", "*.touchbank.com",
    "*.traderepublic.com", "*.transaccionesbancolombia.com", "*.transamerica.com",
    "*.traviscu.org", "*.ubinco.com", "*.ubs.com", "*.uiccu.org", "*.ukrgasbank.com",
    "*.ukrsibbank.com", "*.umcu.org", "*.unicreditbanking.net", "*.unionbank.com",
    "*.unionbankph.com", "*.univest.net", "*.uphold.com", "*.upma.org", "*.usaa.com",
    "*.vakifbankusa.com", "*.vancity.com", "*.vanguard.com", "*.venmo.com", "*.veridiancu.org",
    "*.virginmoney.com", "*.vystarcu.org", "*.wayforpay.com", "*.wealthbar.com",
    "*.wealthfront.com", "*.wealthsimple.com", "*.webbankir.com", "*.wellsfargo.com",
    "*.westconsincu.org", "*.wideup.net", "*.wise.com", "*.wlp-acs.com", "*.wmtransfer.com",
    "*.wooppay.com", "*.wooribank.com", "*.xtb.com", "*.yesrewardz.com", "*.youneedabudget.com",
    "*.zaim.com",
];
