[package]
name = "tollgate-dns"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
arc-swap = { workspace = true }
etherparse = { workspace = true }
hickory-proto = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
thiserror = { workspace = true }
tollgate-common = { workspace = true }
tollgate-filter = { workspace = true }
