//! The Swift names of the M3 exports, checked in the bindings generated by
//! `tooling/scripts/build-core-ios.sh --host`. Run the script first, then
//! `cargo test -p tollgate-ffi --test swift_bindings -- --ignored`.

use std::path::PathBuf;

fn generated_swift() -> String {
    let path = std::env::var_os("TOLLGATE_SWIFT_BINDINGS")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            PathBuf::from(env!("CARGO_MANIFEST_DIR"))
                .join("../../../build/bindings-host/Swift/tollgate_ffi.swift")
        });
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{}: {e}; run build-core-ios.sh --host", path.display()))
}

/// Without whitespace: the generator's spacing (`String)throws  -> UInt32`) is not part
/// of the contract.
fn squeeze(s: &str) -> String {
    s.split_whitespace().collect()
}

/// The declaration lines of `swift` that contain `needle`, without whitespace.
fn declarations(swift: &str, needle: &str) -> Vec<String> {
    swift
        .lines()
        .map(str::trim)
        .filter(|line| line.contains(needle) && !line.starts_with("//"))
        .map(squeeze)
        .collect()
}

#[test]
#[ignore = "needs tooling/scripts/build-core-ios.sh --host"]
fn engine_methods_have_the_expected_swift_names() {
    let swift = generated_swift();
    for (needle, expected) in [
        (
            "func recentEvents(",
            "func recentEvents(limit: UInt32) -> [BlockEvent]",
        ),
        ("func clearEvents(", "func clearEvents()"),
        ("func learnedPins(", "func learnedPins() -> [LearnedPin]"),
        (
            "func forgetPins(",
            "func forgetPins(hosts: [String]) -> UInt32",
        ),
        ("func resetConnections(", "func resetConnections()"),
        (
            "func setLocalResolver(",
            "func setLocalResolver(resolver: LocalResolver?)",
        ),
        ("func setNetwork(", "func setNetwork(network: String)"),
        (
            "func completeLocal(",
            "func completeLocal(id: UInt64, records: [DnsRecord]?) -> [Data]",
        ),
        (
            "func resolve(",
            "func resolve(id: UInt64, name: String, rtype: UInt16, rclass: UInt16)",
        ),
    ] {
        let found = declarations(&swift, needle);
        assert!(
            found.iter().any(|line| line.contains(&squeeze(expected))),
            "{expected}: {found:?}"
        );
    }
}

#[test]
#[ignore = "needs tooling/scripts/build-core-ios.sh --host"]
fn free_functions_have_the_expected_swift_names() {
    let swift = generated_swift();
    for (needle, expected) in [
        (
            "func validateHostPattern(",
            "func validateHostPattern(pattern: String) throws",
        ),
        (
            "func storedLearnedPins(",
            "func storedLearnedPins(dataDir: String) throws -> [LearnedPin]",
        ),
        (
            "func forgetStoredPins(",
            "func forgetStoredPins(dataDir: String, hosts: [String]) throws -> UInt32",
        ),
    ] {
        let found = declarations(&swift, needle);
        assert!(
            found.iter().any(|line| line.contains(&squeeze(expected))),
            "{expected}: {found:?}"
        );
    }
}

/// The stored properties of `public struct <name>`, in order.
fn struct_fields(swift: &str, name: &str) -> Vec<String> {
    let start = swift
        .find(&format!("public struct {name}:"))
        .unwrap_or_else(|| panic!("no struct {name}"));
    let body = &swift[start..];
    let end = body.find("public init(").expect("a public initializer");
    body[..end]
        .lines()
        .map(str::trim)
        .filter_map(|line| line.strip_prefix("public var "))
        .map(squeeze)
        .collect()
}

#[test]
#[ignore = "needs tooling/scripts/build-core-ios.sh --host"]
fn records_have_the_expected_swift_fields() {
    let swift = generated_swift();
    assert_eq!(
        struct_fields(&swift, "BlockEvent"),
        [
            "unixSecs:UInt64",
            "kind:EventKind",
            "host:String",
            "url:String?",
            "sourceHost:String?",
        ]
    );
    assert_eq!(
        struct_fields(&swift, "LearnedPin"),
        ["host:String", "learnedAt:UInt64"]
    );
    assert_eq!(
        struct_fields(&swift, "DnsRecord"),
        ["rtype:UInt16", "rclass:UInt16", "ttl:UInt32", "data:Data"]
    );
    let start = swift.find("public enum EventKind").expect("enum EventKind");
    let body = &swift[start..start + swift[start..].find('}').unwrap()];
    let cases: Vec<&str> = body
        .lines()
        .map(str::trim)
        .filter(|line| line.starts_with("case "))
        .collect();
    assert_eq!(cases, ["case dns", "case request"]);
}
