[package]
name = "tollgate-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "tollgate_ffi"
crate-type = ["lib", "staticlib"]

[dependencies]
log = { workspace = true }
ring = { workspace = true }
thiserror = { workspace = true }
tollgate-mitm = { workspace = true }
uniffi = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
